### ISSUE TITLE
SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by Krachziman** [PapersPleaseLoc/PapersPleaseLoc.github.io#9]
I am consistently getting error described in the title. Tried running tens of different versions of node.js, tried reformatting my usage line in various ways, contantly reinstalling node.js and the entire package, even tried asking chatGPT to create a fix for me but it nothing has solved it for me.

I am enthusiastic about creating an Estonian-language localization for this game, which would be one-of-a-kind since it's a small language, but I am very sad that despite my best efforts, despite investing many hours into finding the solution, I cannot overcome this error.

If anyone has any insight into how to solve this error, I would be immensely grateful.

The in my case, I used the following line, this keeps prompting the error, but even when I use locations that don't exist, I get the same error "SyntaxError: Unexpected token ':'" error:

"node . --csv D:\PPLOC\est.csv --url https://paperspleaseloc.github.io --out D:\PPLOC"

**Comment by Krachziman** [comment]
Nevermind, solved this issue on my own. I used Chrome instead of Firefox to generate csv file, and I downloaded the entire repository and copied the the entire "packer" on hard drive, instead of just putting contents in a randomly named folder.

Everything is working now.

**Comment by kayjay-is-here** [comment]
Good to hear! Sorry I didn't get back to you sooner, I wasn't notified for some reason and I only found this when I was checking up on the repo
